spring:
  application:
    name: personal-audio-backend
  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  cloud:
    aws:
      region:
        static: ap-northeast-2
      sqs:
        enabled: ${AWS_SQS_ENABLED:false}
        listener:
          max-concurrent-messages: ${SQS_MAX_CONCURRENT_MESSAGES:10}
          poll-timeout: 20s

app:
  sqs:
    queue-name: ${SQS_QUEUE_NAME:MyOpenViduQueue-Personal}
  s3:
    bucket: ${S3_BUCKET}

server:
  port: ${SERVER_PORT:8080}
