image: node:20

stages:
  - deploy

deploy_to_vercel:
  stage: deploy
  only:
    - Develop_FE
  tags:
    - ssafy  # SSAFY GitLab Shared Runner 태그 추가
  script:
    - cd Frontend  # (모노레포인 경우 Frontend 폴더로 이동, 단일 프로젝트면 생략 가능)
    - npm install -g vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN