image: node:20

stages:
  - deploy

deploy_to_vercel:
  stage: deploy
  only:
    - Develop_FE
  script:
    - cd Frontend  # 프론트엔드 폴더 위치로 이동 (단일 프로젝트 루트면 이 줄 제거)
    - npm install -g vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN