"""Pipeline public API."""

from __future__ import annotations

from .apply import apply_change_plan
from .chain import (
    M2_PIPELINE_VERSION,
    NODE_GENERATION_PIPELINE_VERSION,
    GenerationOnlyRunResult,
    JudgmentOnlyRunResult,
    MeetingRunResult,
    estimate_credits,
    generation_input_hash,
    run_generation_only,
    run_judgment_only,
    run_meeting,
)
from .errors import (
    ApplyError,
    CandidateNotFoundError,
    CandidateReviewError,
    CandidateStateError,
    CandidateValidationError,
    CandidateVersionConflict,
    StaleVersionError,
)
from .repository import (
    existing_source_keys,
    create_generation_candidates,
    get_candidate_for_review,
    get_node,
    list_candidates_for_request,
    normalize_extraction_items,
    query_candidates_for_review,
    seed_node,
    upsert_meeting,
    upsert_segments,
)
from .service import (
    claim_generation_request,
    finalize_generation_candidates,
    mark_generation_failed,
    payload_hash,
    persist_generation_candidates,
    process_request,
)
from .review import (
    approve_candidate,
    bulk_approve_candidates,
    edit_candidate,
    get_candidate,
    list_candidates,
    reject_candidate,
)

__all__ = [
    "process_request",
    "persist_generation_candidates",
    "claim_generation_request",
    "finalize_generation_candidates",
    "mark_generation_failed",
    "list_candidates",
    "get_candidate",
    "edit_candidate",
    "reject_candidate",
    "approve_candidate",
    "bulk_approve_candidates",
    "payload_hash",
    "apply_change_plan",
    "run_meeting",
    "run_generation_only",
    "run_judgment_only",
    "MeetingRunResult",
    "GenerationOnlyRunResult",
    "JudgmentOnlyRunResult",
    "estimate_credits",
    "generation_input_hash",
    "NODE_GENERATION_PIPELINE_VERSION",
    "M2_PIPELINE_VERSION",
    "ApplyError",
    "StaleVersionError",
    "CandidateReviewError",
    "CandidateNotFoundError",
    "CandidateVersionConflict",
    "CandidateStateError",
    "CandidateValidationError",
    "get_node",
    "seed_node",
    "upsert_meeting",
    "upsert_segments",
    "existing_source_keys",
    "create_generation_candidates",
    "list_candidates_for_request",
    "get_candidate_for_review",
    "query_candidates_for_review",
    "normalize_extraction_items",
]
